spring.application.name=RentalSystem
server.port=8080

server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/RentalSystem
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

jwt-secret=${JWT_SECRET}
jwt-expiration-ms=86400000

spring.jpa.show-sql=true
