spring.application.name=RentalSystem
server.port=8080

server.error.include-stacktrace=never
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/RentalSystem
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

jwt-secret=${JWT_SECRET}
jwt-expiration-ms=86400000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.show-sql=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=50MB

app.admin.email=${ADMIN_USERNAME}
app.admin.password=${ADMIN_PASSWORD}

app.seed.password=Test1234!